version: '3'

services:

  identity.api:
    image: reminders/identity.api:${TAG:-latest}
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile
    depends_on:
      - postgres.data

  reminder.api:
    image: reminders/reminders.api:${TAG:-latest}
    build:
      context: ./src/Services/Reminder/Reminder.API
      dockerfile: Dockerfile
    depends_on:
      - postgres.data

  webmvc:
    image: reminders/webmvc:${TAG:-latest}
    build:
      context: ./src/Web/WebMVC
      dockerfile: Dockerfile
    depends_on:
    - identity.api

  postgres.data:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: Identity