version: '3'

services:

  audit.api:
    image: reminders/audit.api:${TAG:-latest}
    build:
      context: ./src/Services/Audit/Audit.API
      dockerfile: Dockerfile
    depends_on:
      - nosql.data
      - rabbitmq

  identity.api:
    image: reminders/identity.api:${TAG:-latest}
    build:
      context: ./src/Services/Identity/Identity.API
      dockerfile: Dockerfile
    depends_on:
      - postgres.data
      - rabbitmq

  reminder.api:
    image: reminders/reminders.api:${TAG:-latest}
    build:
      context: ./src/Services/Reminder/Reminder.API
      dockerfile: Dockerfile
    depends_on:
      - postgres.data
      - rabbitmq

  webmvc:
    image: reminders/webmvc:${TAG:-latest}
    build:
      context: ./src/Web/WebMVC
      dockerfile: Dockerfile
    depends_on:
    - identity.api
    - reminder.api
    - audit.api

  webstatus:
    image: reminders/webstatus:${TAG:-latest}
    build:
      context: ./src/Web/WebStatus
      dockerfile: Dockerfile
    
  postgres.data:
    image: postgres
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: Identity
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    
  nosql.data:
    image: mongo