version: '3'

services:

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"
